create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  evento text not null,
  sesion_id text not null,
  dispositivo text,
  ruta text,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_created_idx on public.analytics_events(created_at desc);
create index if not exists analytics_events_evento_idx on public.analytics_events(evento,created_at desc);
create index if not exists analytics_events_sesion_idx on public.analytics_events(sesion_id,created_at desc);

alter table public.analytics_events enable row level security;

do $$
declare r record;
begin
  for r in select policyname from pg_policies where schemaname='public' and tablename='analytics_events'
  loop execute format('drop policy if exists %I on public.analytics_events',r.policyname); end loop;
end $$;

create policy analytics_admin_read
on public.analytics_events
for select
to authenticated
using (public.es_admin());

revoke all on public.analytics_events from anon,authenticated;
grant select on public.analytics_events to authenticated;

create or replace function public.registrar_evento_analytics(
  p_evento text,
  p_sesion text,
  p_dispositivo text default null,
  p_ruta text default '/',
  p_meta jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare
  permitidos constant text[] := array['page_view','add_to_cart','checkout_start','order_submitted'];
  ultimo timestamptz;
begin
  if not (p_evento = any(permitidos)) then
    raise exception 'Evento no permitido' using errcode='22023';
  end if;
  if p_sesion is null or length(p_sesion)<8 or length(p_sesion)>100 then
    raise exception 'Sesión inválida' using errcode='22023';
  end if;
  if length(coalesce(p_dispositivo,''))>30 or length(coalesce(p_ruta,''))>120 then
    raise exception 'Datos inválidos' using errcode='22023';
  end if;

  select max(created_at) into ultimo
  from public.analytics_events
  where sesion_id=p_sesion and evento=p_evento;

  if p_evento='page_view' and ultimo is not null and ultimo>now()-interval '5 minutes' then
    return;
  end if;

  insert into public.analytics_events(evento,sesion_id,dispositivo,ruta,meta)
  values(p_evento,p_sesion,p_dispositivo,p_ruta,coalesce(p_meta,'{}'::jsonb));
end;
$$;

revoke all on function public.registrar_evento_analytics(text,text,text,text,jsonb) from public;
grant execute on function public.registrar_evento_analytics(text,text,text,text,jsonb) to anon,authenticated;
